-- Table: public.tenant_users
-- Purpose: Maps Supabase Auth users to specific tenants with roles (owner/admin)
-- Note: tenant_id can be NULL for "orphan" users not yet assigned to a tenant
-- Related: tenants.sql, superadmins.sql

CREATE TABLE public.tenant_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint,  -- NULL allowed for orphan users
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_users_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_users_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id) ON DELETE CASCADE
);

-- Partial unique indexes (handle NULL tenant_id)
CREATE UNIQUE INDEX tenant_users_tenant_user_unique 
ON public.tenant_users (tenant_id, user_id) 
WHERE tenant_id IS NOT NULL;

CREATE UNIQUE INDEX tenant_users_orphan_user_unique 
ON public.tenant_users (user_id) 
WHERE tenant_id IS NULL;

-- Enable RLS (policies defined in ../migrations/policies/tenant_users_policies.sql)
ALTER TABLE public.tenant_users ENABLE ROW LEVEL SECURITY;