-- Table: public.tenants
-- Purpose: Multi-tenant core table - stores tenant metadata and auto-generates schema names
-- Related: tenant_users.sql, schema_migration_history.sql

CREATE TABLE public.tenants (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL UNIQUE CHECK (tenant_id >= 1),
  schema_name text GENERATED ALWAYS AS (
    'tenant_'::text || lpad((tenant_id)::text, 6, '0'::text)
  ) STORED,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text])),
  plan text NOT NULL DEFAULT 'basic'::text CHECK (plan = ANY (ARRAY['basic'::text, 'pro'::text, 'enterprise'::text])),
  revenue numeric NOT NULL DEFAULT 0,
  next_payment timestamp with time zone,
  db_url text,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);

-- Enable RLS (policies defined in ../migrations/policies/tenants_policies.sql)
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;