-- Table: public.superadmins  
-- Purpose: Global platform administrators with elevated privileges
-- Related: tenant_users.sql

CREATE TABLE public.superadmins (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL UNIQUE,
  email text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT superadmins_pkey PRIMARY KEY (id)
);

-- Enable RLS (policies defined in ../migrations/policies/superadmins_policies.sql)
ALTER TABLE public.superadmins ENABLE ROW LEVEL SECURITY;