-- Table: public.schema_migration_history
-- Purpose: Tracks which migrations have been applied to each tenant schema
-- Related: tenants.sql (via schema_name)

CREATE TABLE public.schema_migration_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  schema_name text NOT NULL,
  migration_name text NOT NULL,
  checksum text,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  applied_by uuid,
  CONSTRAINT schema_migration_history_pkey PRIMARY KEY (id),
  CONSTRAINT schema_migration_unique UNIQUE (schema_name, migration_name)
);

-- Enable RLS (policies defined in ../migrations/policies/schema_migration_history_policies.sql)
ALTER TABLE public.schema_migration_history ENABLE ROW LEVEL SECURITY;