-- Tenant Schema Template
-- Purpose: Creates all necessary tables for a tenant schema
-- Usage: Called by create_store_tenant() after schema creation

CREATE OR REPLACE FUNCTION public.apply_tenant_template(p_schema_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Create all tenant tables with proper schema qualification
  EXECUTE format('
    -- Table: employees (usuarios internos del tenant)
    CREATE TABLE IF NOT EXISTS %I.user_account (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username varchar(30) NOT NULL UNIQUE,
      password varchar(100) NOT NULL,
      rol varchar(30) NOT NULL,
      fecha_creacion timestamptz DEFAULT now() NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_user_account_username ON %I.user_account(username);

    -- Table: clientes
    CREATE TABLE IF NOT EXISTS %I.clientes (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre varchar(50) NOT NULL,
      email varchar(100),
      telefono varchar(20),
      fecha_registro timestamptz DEFAULT now()
    );

    -- Table: insumos (inventario/materias primas)
    CREATE TABLE IF NOT EXISTS %I.insumos (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre varchar(50) NOT NULL UNIQUE,
      unidad_medida varchar(20) NOT NULL,
      costo numeric(10,3) DEFAULT 0 NOT NULL,
      stock_actual numeric(10,3) DEFAULT 0 NOT NULL,
      nota varchar(100)
    );
    CREATE INDEX IF NOT EXISTS idx_insumos_nombre ON %I.insumos(nombre);

    -- Table: productos
    CREATE TABLE IF NOT EXISTS %I.productos (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre varchar(30) NOT NULL,
      precio numeric(10,3) NOT NULL,
      nota varchar(100)
    );

    -- Table: recetas (1:1 con productos)
    CREATE TABLE IF NOT EXISTS %I.recetas (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      producto_id bigint NOT NULL REFERENCES %I.productos(id) ON DELETE CASCADE,
      nota varchar(100)
    );

    -- Table: receta_insumo (many-to-many entre recetas e insumos)
    CREATE TABLE IF NOT EXISTS %I.receta_insumo (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      receta_id bigint NOT NULL REFERENCES %I.recetas(id) ON DELETE CASCADE,
      insumo_id bigint NOT NULL REFERENCES %I.insumos(id) ON DELETE CASCADE,
      cantidad numeric(10,3) NOT NULL,
      nota varchar(100)
    );

    -- Table: mesas
    CREATE TABLE IF NOT EXISTS %I.mesas (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre varchar(30) NOT NULL,
      ocupada boolean DEFAULT false NOT NULL,
      notas varchar(100)
    );

    -- Table: ordenes
    CREATE TABLE IF NOT EXISTS %I.ordenes (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      mesa_id bigint NOT NULL REFERENCES %I.mesas(id) ON DELETE RESTRICT,
      cliente_id bigint REFERENCES %I.clientes(id) ON DELETE SET NULL,
      estado varchar(30) DEFAULT ''abierta'' NOT NULL,
      fecha_creacion timestamptz DEFAULT now() NOT NULL,
      total numeric(10,3) DEFAULT 0 NOT NULL,
      propina numeric(10,3) DEFAULT 0 NOT NULL,
      tipo_pago varchar(30),
      es_factura_electronica boolean DEFAULT false NOT NULL
    );

    -- Table: detalle_orden (items de cada orden)
    CREATE TABLE IF NOT EXISTS %I.detalle_orden (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      orden_id bigint NOT NULL REFERENCES %I.ordenes(id) ON DELETE CASCADE,
      producto_id bigint NOT NULL REFERENCES %I.productos(id) ON DELETE RESTRICT,
      cantidad integer NOT NULL,
      precio_unitario numeric(10,3) NOT NULL,
      subtotal numeric(10,3) NOT NULL,
      nota varchar(100)
    );
  ', 
  p_schema_name, p_schema_name,  -- user_account
  p_schema_name,                  -- clientes
  p_schema_name, p_schema_name,   -- insumos
  p_schema_name,                  -- productos
  p_schema_name, p_schema_name,   -- recetas
  p_schema_name, p_schema_name, p_schema_name,  -- receta_insumo
  p_schema_name,                  -- mesas
  p_schema_name, p_schema_name, p_schema_name,  -- ordenes
  p_schema_name, p_schema_name, p_schema_name   -- detalle_orden
  );
END;
$$;

-- Hardening: revoke public, grant only service_role
REVOKE ALL ON FUNCTION public.apply_tenant_template(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_tenant_template(text) TO service_role;